---
- name: Add the newly created host so that we can further contact it
  add_host:
    name: "{{ item.public_ip }}"
    groups: webservers
  with_items: "{{ ec2.instances }}"

- name: Add tag to Instance(s)
  ec2_tag:
    resource: "{{ item.id }}" 
    region: "{{ region }}" 
    state: "present"
  with_items: "{{ ec2.instances }}"
  args:
    tags:
      Type: docker

- name: Wait for SSH to come up
 wait_for:
#    host: "{{ item.public_ip }}"
#    port: 22 
     timeout: 40
#    state: started 
  with_items: "{{ ec2.instances }}"
