---
# tasks file for install-docker
- name: Add Docker GPG key
  apt_key: url="{{ docker_key }}"

- name: Add Docker APT repository
  apt_repository:
    repo: "{{ docker_repo }}"

- name: Install list of packages
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'docker-ce']
    state: present
    update_cache: yes

- name: Add user to docker group
  shell: "sudo usermod -aG docker $USER"